start = events
events = element events { track+ }
track = element track { event+, attribute type { "1" | "2" | "3" }, name }
name  = attribute name { text }
event = element event { title, date+, description, lat, lon }
title = element title { text }
date = element date { attribute type { "start" | "end" }, year, month?, day?, era? }
description = element description { text }
lat = element lat { xsd:float }
lon = element lon { xsd:float }
year = element year { xsd:int }
month = element month { xsd:int }
day = element day { xsd:int }
era = element era { "BC" | "AD" }